/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AttemptTimeline: typeof import('./src/components/AttemptTimeline.vue')['default']
    CircuitBreakerCard: typeof import('./src/components/CircuitBreakerCard.vue')['default']
    CreatePaymentDialog: typeof import('./src/components/CreatePaymentDialog.vue')['default']
    DemoScenarioRunner: typeof import('./src/components/DemoScenarioRunner.vue')['default']
    GatewayModeSelector: typeof import('./src/components/GatewayModeSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
  }
}
