/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttemptTimeline: typeof import('./src/components/AttemptTimeline.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    CircuitBreakerCard: typeof import('./src/components/CircuitBreakerCard.vue')['default']
    Column: typeof import('primevue/column')['default']
    CreatePaymentDialog: typeof import('./src/components/CreatePaymentDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DemoScenarioRunner: typeof import('./src/components/DemoScenarioRunner.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    GatewayModeSelector: typeof import('./src/components/GatewayModeSelector.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
